### ISSUE TITLE
Implement Authentication feature

### ISSUE THREAD

**Issue by spksoft** [spksoft/maria#1]

**Comment by 0pdd** [comment]
@spksoft the puzzle [#2](https://github.com/spksoft/maria/issues/2) is still not solved.

**Comment by 0pdd** [comment]
@spksoft 2 puzzles [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3) are still not solved.

**Comment by 0pdd** [comment]
@spksoft the puzzle [#2](https://github.com/spksoft/maria/issues/2) is still not solved; solved: [#3](https://github.com/spksoft/maria/issues/3).

**Comment by 0pdd** [comment]
@spksoft all 2 puzzles are solved here: [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3).

**Comment by 0pdd** [comment]
@spksoft the puzzle [#5](https://github.com/spksoft/maria/issues/5) is still not solved; solved: [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3).

**Comment by 0pdd** [comment]
@spksoft 2 puzzles [#5](https://github.com/spksoft/maria/issues/5), [#6](https://github.com/spksoft/maria/issues/6) are still not solved; solved: [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3).

**Comment by 0pdd** [comment]
@spksoft the puzzle [#6](https://github.com/spksoft/maria/issues/6) is still not solved; solved: [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3), [#5](https://github.com/spksoft/maria/issues/5).

**Comment by 0pdd** [comment]
@spksoft all 4 puzzles are solved here: [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3), [#5](https://github.com/spksoft/maria/issues/5), [#6](https://github.com/spksoft/maria/issues/6).

**Comment by 0pdd** [comment]
@spksoft the puzzle [#8](https://github.com/spksoft/maria/issues/8) is still not solved; solved: [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3), [#5](https://github.com/spksoft/maria/issues/5), [#6](https://github.com/spksoft/maria/issues/6).

**Comment by 0pdd** [comment]
@spksoft all 5 puzzles are solved here: [#2](https://github.com/spksoft/maria/issues/2), [#3](https://github.com/spksoft/maria/issues/3), [#5](https://github.com/spksoft/maria/issues/5), [#6](https://github.com/spksoft/maria/issues/6), [#8](https://github.com/spksoft/maria/issues/8).
