### ISSUE TITLE
เพิ่มระบบ Login โดยต่อกับ Firebase

### ISSUE THREAD

**Issue by spksoft** [spksoft/maria#11]

**Comment by 0pdd** [comment]
@spksoft 3 puzzles [#12](https://github.com/spksoft/maria/issues/12), [#13](https://github.com/spksoft/maria/issues/13), [#14](https://github.com/spksoft/maria/issues/14) are still not solved.

**Comment by 0pdd** [comment]
@spksoft 2 puzzles [#12](https://github.com/spksoft/maria/issues/12), [#14](https://github.com/spksoft/maria/issues/14) are still not solved; solved: [#13](https://github.com/spksoft/maria/issues/13).

**Comment by 0pdd** [comment]
@spksoft all 3 puzzles are solved here: [#12](https://github.com/spksoft/maria/issues/12), [#13](https://github.com/spksoft/maria/issues/13), [#14](https://github.com/spksoft/maria/issues/14).
